# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

jobs:
  itamae:
    docker:
      - image: sue445/vagrant-aws
    working_directory: ~/app
    environment:
      PRIVATE_KEY_PATH: /root/.ssh/id_rsa_60edd9e6c0494ef33b67c64e20713892

    steps:
      - checkout
      - run:
          name: Setup workspace
          command: |
            git submodule sync
            git submodule update --init
            mkdir -p 700 ~/.ssh/
      - add_ssh_keys:
          fingerprints:
            - "60:ed:d9:e6:c0:49:4e:f3:3b:67:c6:4e:20:71:38:92"
      - run:
          command: vagrant up --provider=aws
          no_output_timeout: 10m
      - run:
          command: vagrant destroy -f
          when: always

  rubocop:
    docker:
      - image: circleci/ruby

    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile.lock" }}
            - v1-bundle-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: bundle install
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle clean
      - save_cache:
          key: v1-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/app/vendor/bundle
      - run: bundle exec rubocop

  packer:
    docker:
      - image: circleci/ruby

    working_directory: ~/app
    environment:
      USER: circleci
      PRIVATE_KEY_PATH: /home/circleci/.ssh/id_rsa_60edd9e6c0494ef33b67c64e20713892
      PACKER_VERSION: 1.2.5
      PACKER_PROVISIONER_SERVERSPEC_VERSION: 1.0.0

    steps:
      - checkout
      - run:
          name: Setup workspace
          command: |
            git submodule sync
            git submodule update --init
            mkdir -p 700 ~/.ssh/
      - run:
          name: git config
          command: |
            git config push.default current
            git config user.name "CircleCI"
            git config user.email ${EMAIL}
      - add_ssh_keys:
          fingerprints:
            - "60:ed:d9:e6:c0:49:4e:f3:3b:67:c6:4e:20:71:38:92"
      - run:
          name: Install git-archive-all
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip
            sudo pip install git-archive-all
      - run:
          name: Install packer
          command: |
            wget "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip" -O /tmp/packer.zip
            sudo unzip -o -d /usr/local/bin /tmp/packer.zip
            sudo chmod +x /usr/local/bin/packer
      - run:
          name: Install packer-provisioner-serverspec
          command: |
            wget "https://github.com/sue445/packer-provisioner-serverspec/releases/download/v${PACKER_PROVISIONER_SERVERSPEC_VERSION}/packer-provisioner-serverspec_linux_amd64" -O /tmp/packer-provisioner-serverspec
            sudo mv /tmp/packer-provisioner-serverspec /usr/local/bin
            sudo chmod +x /usr/local/bin/packer-provisioner-serverspec
      - restore_cache:
          keys:
            - v1-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile.lock" }}
            - v1-bundle-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: bundle install
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle clean
      - save_cache:
          key: v1-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/app/vendor/bundle
      - run:
          name: packer build
          command: |
            AMI_NAME="techbookfest5-$(date +'%Y%m%d-%H%M%S')"
            echo "AMI_NAME=${AMI_NAME}"
            bundle exec packer build -var "ami_name=${AMI_NAME}" packer/aws.json
            git tag -a $AMI_NAME -m $AMI_NAME
            git push origin --tags

workflows:
  version: 2

  build:
    jobs:
      - itamae
      - rubocop
      - hold_packer:
          type: approval
          requires:
            - itamae
            - rubocop
          filters:
            branches:
              only: master
      - packer:
          requires:
            - hold_packer
