# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: sue445/vagrant-aws
    working_directory: ~/app
    environment:
      PRIVATE_KEY_PATH: /root/.ssh/id_rsa_60edd9e6c0494ef33b67c64e20713892

    steps:
      - checkout
      - run: mkdir -p 700 /root/.ssh/
      - add_ssh_keys:
          fingerprints:
            - "60:ed:d9:e6:c0:49:4e:f3:3b:67:c6:4e:20:71:38:92"
      - run:
          command: vagrant up --provider=aws
          no_output_timeout: 3m
      - run:
          command: vagrant destroy -f
          when: always

workflows:
  version: 2

  build:
    jobs:
      - build
